version: '3.1'
services:
  app:
    container_name: app-stackoverflow
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      # This overrides spring.datasource.url in your application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/stackoverflow
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Secret@2026

  dbpostgresql:
    image: postgres:18-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=Secret@2026
      - POSTGRES_USER=admin
      - POSTGRES_DB=stackoverflow